### ISSUE TITLE
can't mark as read or delete notification in subform

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#359]
When Kim and I use this subform
![image](https://user-images.githubusercontent.com/49287076/77542480-3b65a400-6e74-11ea-94ce-fe3fbabde618.png)
it doesn't mark a message as read if we just hit "close" and it doesn't delete a message when we hit "delete" (though if I do a control-F5 after this subform closes, the message I was trying to delete does disappear, but a message that I hit "close" on and thus should be marked as read stays as unread after a control-F5)

**Comment by BlakeDraper** [comment]
@aaronstephenson last commit seems to have introduced a bug. Notification PATCH error. 

![image](https://user-images.githubusercontent.com/6978380/77543474-be3b2e80-6e75-11ea-9f61-1f3049d7bcab.png)

```
{
	"id":254,
	"read":true
}
```


```
Traceback:

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/rest_framework/viewsets.py" in view
  114.             return self.dispatch(request, *args, **kwargs)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/rest_framework/views.py" in dispatch
  505.             response = self.handle_exception(exc)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/rest_framework/views.py" in handle_exception
  465.             self.raise_uncaught_exception(exc)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/rest_framework/views.py" in raise_uncaught_exception
  476.         raise exc

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/rest_framework/views.py" in dispatch
  502.             response = handler(request, *args, **kwargs)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/rest_framework/mixins.py" in partial_update
  82.         return self.update(request, *args, **kwargs)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/rest_framework/mixins.py" in update
  68.         self.perform_update(serializer)

File "/var/www/whispersservices_django/whispersservices/views.py" in perform_update
  144.             serializer.save(modified_by=self.request.user)

File "/var/www/whispersservices_django/env/lib/python3.5/site-packages/rest_framework/serializers.py" in save
  207.             self.instance = self.update(self.instance, validated_data)

File "/var/www/whispersservices_django/whispersservices/serializers.py" in update
  3986.         instance.read  = validated_data.get('read', instance.request_response)
```

**Comment by aaronstephenson** [comment]
Fixed in 218f578a

**Comment by JChipault** [comment]
@aaronstephenson still not working. The thing not working the most consistently is the "delete" button in the subform, but the "mark as unread" and "close" are working spottily for me. Tested in both firefox and chrome
